---
- name: Generate an OpenSSH keypair with the default values (4096 bits, rsa)
  community.crypto.openssh_keypair:
    path: '{{ item.key }}'
    mode: '0600'
    owner: '{{ gdk_user }}'

- name: Register public key to variable
  ansible.builtin.command: "cat {{ item.key }}.pub"
  register: pubkey
  changed_when: false

- name: Add a new deploy key to a GitHub repository, use an OAuth2 token to authenticate
  community.general.github_deploy_key:
    owner: "{{ item.owner }}"
    repository: "{{ item.repo }}"
    name: "{{ item.deploy_keyname }}"
    key: "{{ pubkey.stdout | trim }}"
    token: "{{ item.token }}"
    state: "{{ item.state | default('present') }}"
  tags: notest
