---

- name: Prepare
  hosts: all
  gather_facts: true
  tasks:
    - name: "Ensure .ssh directory exists"
      ansible.builtin.file:
        path: /root/.ssh
        state: directory
        mode: '0700'
